[package]
name = "soketto"
version = "0.2.3"
authors = ["Parity Technologies <admin@parity.io>", "Jason Ozias <jason.g.ozias@gmail.com>"]
description = "A websocket protocol implementation as as set of tokio codecs."
keywords = ["tokio", "websocket", "codec"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/paritytech/soketto"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
deflate = ["flate2"]

[dependencies]
base64 = "0.10.1"
flate2 = { version = "1.0.8", features = ["zlib"], default-features = false, optional = true }
futures-preview = "0.3.0-alpha.18"
http = "0.1.17"
httparse = "1.3.3"
log = "0.4.6"
rand = "0.6.5"
sha1 = "0.6.0"
smallvec = "0.6.9"

[dev-dependencies]
assert_matches = "1.3.0"
async-std = "0.99"
env_logger = "0.6.1"
quickcheck = "0.8.5"
